var searchData=
[
  ['end_0',['end',['../classgg_1_1GgTrackball.html#a4f56d59aadba0be3e8196971828382a1',1,'gg::GgTrackball']]],
  ['euler_1',['euler',['../classgg_1_1GgQuaternion.html#abdbd693a6cd020ed36293d3aec1b528c',1,'gg::GgQuaternion::euler(GLfloat heading, GLfloat pitch, GLfloat roll) const'],['../classgg_1_1GgQuaternion.html#a65a6c0126b5f8a857046f8e1defca7cc',1,'gg::GgQuaternion::euler(const GLfloat *e) const'],['../classgg_1_1GgQuaternion.html#a67653ac2a70b598147b4f2b1fd9cccab',1,'gg::GgQuaternion::euler(const GgVector &amp;e) const']]],
  ['eye_2',['eye',['../md_OPENXR.html#autotoc_md20',1,'&lt;span class=&quot;tt&quot;&gt;void commit(int eye)&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md18',1,'&lt;span class=&quot;tt&quot;&gt;void select(int eye)&lt;/span&gt;']]],
  ['eye_200_20const_3',['eye 0 const',['../md_OPENXR.html#autotoc_md32',1,'&lt;span class=&quot;tt&quot;&gt;GLfloat getAspect(int eye = 0) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md31',1,'&lt;span class=&quot;tt&quot;&gt;GLsizei getWidth(int eye = 0) const&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;GLsizei getHeight(int eye = 0) const&lt;/span&gt;']]],
  ['eye_200_20const_20glsizei_20getheight_20int_20eye_200_20const_4',['&lt;span class=&quot;tt&quot;&gt;GLsizei getWidth(int eye = 0) const&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;GLsizei getHeight(int eye = 0) const&lt;/span&gt;',['../md_OPENXR.html#autotoc_md31',1,'']]],
  ['eye_20const_5',['eye const',['../md_OPENXR.html#autotoc_md29',1,'&lt;span class=&quot;tt&quot;&gt;const XrFovf&amp;amp; getFov(int eye) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md30',1,'&lt;span class=&quot;tt&quot;&gt;const XrPosef&amp;amp; getPose(int eye) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md26',1,'&lt;span class=&quot;tt&quot;&gt;GgMatrix getPoseMatrix(int eye) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md25',1,'&lt;span class=&quot;tt&quot;&gt;GgMatrix getViewMatrix(int eye) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md28',1,'&lt;span class=&quot;tt&quot;&gt;GgQuaternion getOrientation(int eye) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md27',1,'&lt;span class=&quot;tt&quot;&gt;GgVector getPosition(int eye) const&lt;/span&gt;']]],
  ['eye_20glfloat_20screen_20glfloat_20position_20glfloat_20orientation_6',['&lt;span class=&quot;tt&quot;&gt;void select(int eye, GLfloat* screen, GLfloat* position, GLfloat* orientation)&lt;/span&gt;',['../md_OPENXR.html#autotoc_md19',1,'']]],
  ['eye_20glfloat_20znear_200_201f_20glfloat_20zfar_20100_200f_20const_7',['&lt;span class=&quot;tt&quot;&gt;GgMatrix getProjectionMatrix(int eye, GLfloat zNear = 0.1f, GLfloat zFar = 100.0f) const&lt;/span&gt;',['../md_OPENXR.html#autotoc_md24',1,'']]]
];
