var searchData=
[
  ['imconfig_20h_20の変更点_0',['imconfig.h の変更点',['../md_README.html#autotoc_md84',1,'']]],
  ['imgui_20を使う場合_1',['Dear ImGui を使う場合',['../md_README.html#autotoc_md83',1,'']]],
  ['initialize_20const_20window_20window_20xrreferencespacetype_20spacetype_20xr_5freference_5fspace_5ftype_5fstage_2',['&lt;span class=&quot;tt&quot;&gt;static OpenXR&amp;amp; initialize(const Window&amp;amp; window, XrReferenceSpaceType spaceType = XR_REFERENCE_SPACE_TYPE_STAGE)&lt;/span&gt;',['../md_OPENXR.html#autotoc_md13',1,'']]],
  ['int_20eye_3',['int eye',['../md_OPENXR.html#autotoc_md20',1,'&lt;span class=&quot;tt&quot;&gt;void commit(int eye)&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md18',1,'&lt;span class=&quot;tt&quot;&gt;void select(int eye)&lt;/span&gt;']]],
  ['int_20eye_200_20const_4',['int eye 0 const',['../md_OPENXR.html#autotoc_md32',1,'&lt;span class=&quot;tt&quot;&gt;GLfloat getAspect(int eye = 0) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md31',1,'&lt;span class=&quot;tt&quot;&gt;GLsizei getWidth(int eye = 0) const&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;GLsizei getHeight(int eye = 0) const&lt;/span&gt;']]],
  ['int_20eye_200_20const_20glsizei_20getheight_20int_20eye_200_20const_5',['&lt;span class=&quot;tt&quot;&gt;GLsizei getWidth(int eye = 0) const&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;GLsizei getHeight(int eye = 0) const&lt;/span&gt;',['../md_OPENXR.html#autotoc_md31',1,'']]],
  ['int_20eye_20const_6',['int eye const',['../md_OPENXR.html#autotoc_md29',1,'&lt;span class=&quot;tt&quot;&gt;const XrFovf&amp;amp; getFov(int eye) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md30',1,'&lt;span class=&quot;tt&quot;&gt;const XrPosef&amp;amp; getPose(int eye) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md26',1,'&lt;span class=&quot;tt&quot;&gt;GgMatrix getPoseMatrix(int eye) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md25',1,'&lt;span class=&quot;tt&quot;&gt;GgMatrix getViewMatrix(int eye) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md28',1,'&lt;span class=&quot;tt&quot;&gt;GgQuaternion getOrientation(int eye) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md27',1,'&lt;span class=&quot;tt&quot;&gt;GgVector getPosition(int eye) const&lt;/span&gt;']]],
  ['int_20eye_20glfloat_20screen_20glfloat_20position_20glfloat_20orientation_7',['&lt;span class=&quot;tt&quot;&gt;void select(int eye, GLfloat* screen, GLfloat* position, GLfloat* orientation)&lt;/span&gt;',['../md_OPENXR.html#autotoc_md19',1,'']]],
  ['int_20eye_20glfloat_20znear_200_201f_20glfloat_20zfar_20100_200f_20const_8',['&lt;span class=&quot;tt&quot;&gt;GgMatrix getProjectionMatrix(int eye, GLfloat zNear = 0.1f, GLfloat zFar = 100.0f) const&lt;/span&gt;',['../md_OPENXR.html#autotoc_md24',1,'']]],
  ['int_20hand_20const_9',['int hand const',['../md_OPENXR.html#autotoc_md47',1,'&lt;span class=&quot;tt&quot;&gt;bool getPrimaryButton(int hand) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md48',1,'&lt;span class=&quot;tt&quot;&gt;bool getSecondaryButton(int hand) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md46',1,'&lt;span class=&quot;tt&quot;&gt;bool getThumbstickClick(int hand) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md36',1,'&lt;span class=&quot;tt&quot;&gt;bool isTracked(int hand) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md44',1,'&lt;span class=&quot;tt&quot;&gt;float getGrip(int hand) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md43',1,'&lt;span class=&quot;tt&quot;&gt;float getTrigger(int hand) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md38',1,'&lt;span class=&quot;tt&quot;&gt;GgMatrix getAimMatrix(int hand) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md37',1,'&lt;span class=&quot;tt&quot;&gt;GgMatrix getGripMatrix(int hand) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md40',1,'&lt;span class=&quot;tt&quot;&gt;GgVector getAimPosition(int hand) const&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;GgQuaternion getAimOrientation(int hand) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md39',1,'&lt;span class=&quot;tt&quot;&gt;GgVector getGripPosition(int hand) const&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;GgQuaternion getGripOrientation(int hand) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md45',1,'&lt;span class=&quot;tt&quot;&gt;std::array&amp;lt;float, 2&amp;gt; getThumbstick(int hand) const&lt;/span&gt;']]],
  ['int_20hand_20const_20ggquaternion_20getaimorientation_20int_20hand_20const_10',['&lt;span class=&quot;tt&quot;&gt;GgVector getAimPosition(int hand) const&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;GgQuaternion getAimOrientation(int hand) const&lt;/span&gt;',['../md_OPENXR.html#autotoc_md40',1,'']]],
  ['int_20hand_20const_20ggquaternion_20getgriporientation_20int_20hand_20const_11',['&lt;span class=&quot;tt&quot;&gt;GgVector getGripPosition(int hand) const&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;GgQuaternion getGripOrientation(int hand) const&lt;/span&gt;',['../md_OPENXR.html#autotoc_md39',1,'']]],
  ['int_20hand_20float_20durationseconds_200_201f_20float_20frequency_20xr_5ffrequency_5funspecified_20float_20amplitude_200_205f_12',['&lt;span class=&quot;tt&quot;&gt;void applyHapticVibration(int hand, float durationSeconds = 0.1f, float frequency = XR_FREQUENCY_UNSPECIFIED, float amplitude = 0.5f)&lt;/span&gt;',['../md_OPENXR.html#autotoc_md50',1,'']]],
  ['int_20hand_20hand_3a_3aleft_20const_13',['&lt;span class=&quot;tt&quot;&gt;bool getMenuButton(int hand = Hand::Left) const&lt;/span&gt;',['../md_OPENXR.html#autotoc_md49',1,'']]],
  ['invert_14',['invert',['../classgg_1_1GgMatrix.html#a899cc6209060b580bc14b1a45f9c302c',1,'gg::GgMatrix::invert()'],['../classgg_1_1GgQuaternion.html#ae76a0626497b4b3c203be499169a49af',1,'gg::GgQuaternion::invert()']]],
  ['istracked_20int_20hand_20const_15',['&lt;span class=&quot;tt&quot;&gt;bool isTracked(int hand) const&lt;/span&gt;',['../md_OPENXR.html#autotoc_md36',1,'']]]
];
