var searchData=
[
  ['h_20の変更点_0',['imconfig.h の変更点',['../md_README.html#autotoc_md84',1,'']]],
  ['hand_20const_1',['hand const',['../md_OPENXR.html#autotoc_md47',1,'&lt;span class=&quot;tt&quot;&gt;bool getPrimaryButton(int hand) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md48',1,'&lt;span class=&quot;tt&quot;&gt;bool getSecondaryButton(int hand) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md46',1,'&lt;span class=&quot;tt&quot;&gt;bool getThumbstickClick(int hand) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md36',1,'&lt;span class=&quot;tt&quot;&gt;bool isTracked(int hand) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md44',1,'&lt;span class=&quot;tt&quot;&gt;float getGrip(int hand) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md43',1,'&lt;span class=&quot;tt&quot;&gt;float getTrigger(int hand) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md38',1,'&lt;span class=&quot;tt&quot;&gt;GgMatrix getAimMatrix(int hand) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md37',1,'&lt;span class=&quot;tt&quot;&gt;GgMatrix getGripMatrix(int hand) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md40',1,'&lt;span class=&quot;tt&quot;&gt;GgVector getAimPosition(int hand) const&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;GgQuaternion getAimOrientation(int hand) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md39',1,'&lt;span class=&quot;tt&quot;&gt;GgVector getGripPosition(int hand) const&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;GgQuaternion getGripOrientation(int hand) const&lt;/span&gt;'],['../md_OPENXR.html#autotoc_md45',1,'&lt;span class=&quot;tt&quot;&gt;std::array&amp;lt;float, 2&amp;gt; getThumbstick(int hand) const&lt;/span&gt;']]],
  ['hand_20const_20ggquaternion_20getaimorientation_20int_20hand_20const_2',['&lt;span class=&quot;tt&quot;&gt;GgVector getAimPosition(int hand) const&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;GgQuaternion getAimOrientation(int hand) const&lt;/span&gt;',['../md_OPENXR.html#autotoc_md40',1,'']]],
  ['hand_20const_20ggquaternion_20getgriporientation_20int_20hand_20const_3',['&lt;span class=&quot;tt&quot;&gt;GgVector getGripPosition(int hand) const&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;GgQuaternion getGripOrientation(int hand) const&lt;/span&gt;',['../md_OPENXR.html#autotoc_md39',1,'']]],
  ['hand_20float_20durationseconds_200_201f_20float_20frequency_20xr_5ffrequency_5funspecified_20float_20amplitude_200_205f_4',['&lt;span class=&quot;tt&quot;&gt;void applyHapticVibration(int hand, float durationSeconds = 0.1f, float frequency = XR_FREQUENCY_UNSPECIFIED, float amplitude = 0.5f)&lt;/span&gt;',['../md_OPENXR.html#autotoc_md50',1,'']]],
  ['hand_20hand_3a_3aleft_20const_5',['&lt;span class=&quot;tt&quot;&gt;bool getMenuButton(int hand = Hand::Left) const&lt;/span&gt;',['../md_OPENXR.html#autotoc_md49',1,'']]],
  ['hand_3a_3aleft_20const_6',['&lt;span class=&quot;tt&quot;&gt;bool getMenuButton(int hand = Hand::Left) const&lt;/span&gt;',['../md_OPENXR.html#autotoc_md49',1,'']]],
  ['header_5fstr_7',['HEADER_STR',['../main_8cpp.html#a9eb08c4f3ad005333d49aa2299e5c7c3',1,'main.cpp']]]
];
