var functions_dup =
[
    [ "a", "functions.html", null ],
    [ "app", "functions_a.html", null ],
    [ "b", "functions_b.html", null ],
    [ "buf", "functions_b.html", null ],
    [ "c", "functions_c.html", null ],
    [ "col", "functions_c.html", null ],
    [ "d", "functions_d.html", null ],
    [ "e", "functions_e.html", null ],
    [ "ele", "functions_e.html", null ],
    [ "f", "functions_f.html", null ],
    [ "g", "functions_g.html", null ],
    [ "i", "functions_i.html", null ],
    [ "l", "functions_l.html", null ],
    [ "m", "functions_m.html", null ],
    [ "mat", "functions_m.html", null ],
    [ "n", "functions_n.html", null ],
    [ "nor", "functions_n.html", null ],
    [ "o", "functions_o.html", null ],
    [ "p", "functions_p.html", null ],
    [ "poi", "functions_p.html", null ],
    [ "qua", "functions_q.html", null ],
    [ "r", "functions_r.html", null ],
    [ "s", "functions_s.html", null ],
    [ "sha", "functions_s.html", null ],
    [ "sim", "functions_s.html", null ],
    [ "t", "functions_t.html", null ],
    [ "tex", "functions_t.html", null ],
    [ "tra", "functions_t.html", null ],
    [ "tri", "functions_t.html", null ],
    [ "u", "functions_u.html", null ],
    [ "uni", "functions_u.html", null ],
    [ "vec", "functions_v.html", null ],
    [ "ver", "functions_v.html", null ],
    [ "w", "functions_w.html", null ],
    [ "~", "functions_~.html", null ]
];