/*
 @licstart  The following is the entire license notice for the JavaScript code in this file.

 The MIT License (MIT)

 Copyright (C) 1997-2020 by Dimitri van Heesch

 Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 and associated documentation files (the "Software"), to deal in the Software without restriction,
 including without limitation the rights to use, copy, modify, merge, publish, distribute,
 sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all copies or
 substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
 BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

 @licend  The above is the entire license notice for the JavaScript code in this file
*/
var menudata={children:[
{text:"総合概要",url:"index.html"},
{text:"諸情報",url:"pages.html"},
{text:"名前空間",url:"namespaces.html",children:[
{text:"名前空間一覧",url:"namespaces.html"},
{text:"名前空間メンバ",url:"namespacemembers.html",children:[
{text:"全て",url:"namespacemembers.html",children:[
{text:"_",url:"namespacemembers.html#index__5F"},
{text:"arr",url:"namespacemembers.html#index_a"},
{text:"b",url:"namespacemembers.html#index_b"},
{text:"buf",url:"namespacemembers.html#index_b"},
{text:"con",url:"namespacemembers.html#index_c"},
{text:"cre",url:"namespacemembers.html#index_c"},
{text:"cro",url:"namespacemembers.html#index_c"},
{text:"dis",url:"namespacemembers.html#index_d"},
{text:"dot",url:"namespacemembers.html#index_d"},
{text:"ele",url:"namespacemembers.html#index_e"},
{text:"ell",url:"namespacemembers.html#index_e"},
{text:"eul",url:"namespacemembers.html#index_e"},
{text:"fru",url:"namespacemembers.html#index_f"},
{text:"ide",url:"namespacemembers.html#index_i"},
{text:"ini",url:"namespacemembers.html#index_i"},
{text:"inv",url:"namespacemembers.html#index_i"},
{text:"l",url:"namespacemembers.html#index_l"},
{text:"len",url:"namespacemembers.html#index_l"},
{text:"loa",url:"namespacemembers.html#index_l"},
{text:"loo",url:"namespacemembers.html#index_l"},
{text:"m",url:"namespacemembers.html#index_m"},
{text:"mat",url:"namespacemembers.html#index_m"},
{text:"nor",url:"namespacemembers.html#index_n"},
{text:"o",url:"namespacemembers.html#index_o"},
{text:"ort",url:"namespacemembers.html#index_o"},
{text:"per",url:"namespacemembers.html#index_p"},
{text:"poi",url:"namespacemembers.html#index_p"},
{text:"qua",url:"namespacemembers.html#index_q"},
{text:"rea",url:"namespacemembers.html#index_r"},
{text:"rec",url:"namespacemembers.html#index_r"},
{text:"rot",url:"namespacemembers.html#index_r"},
{text:"sav",url:"namespacemembers.html#index_s"},
{text:"sca",url:"namespacemembers.html#index_s"},
{text:"sle",url:"namespacemembers.html#index_s"},
{text:"tra",url:"namespacemembers.html#index_t"}]},
{text:"関数",url:"namespacemembers_func.html",children:[
{text:"_",url:"namespacemembers_func.html#index__5F"},
{text:"arr",url:"namespacemembers_func.html#index_a"},
{text:"con",url:"namespacemembers_func.html#index_c"},
{text:"cre",url:"namespacemembers_func.html#index_c"},
{text:"cro",url:"namespacemembers_func.html#index_c"},
{text:"dis",url:"namespacemembers_func.html#index_d"},
{text:"dot",url:"namespacemembers_func.html#index_d"},
{text:"ele",url:"namespacemembers_func.html#index_e"},
{text:"ell",url:"namespacemembers_func.html#index_e"},
{text:"eul",url:"namespacemembers_func.html#index_e"},
{text:"fru",url:"namespacemembers_func.html#index_f"},
{text:"ide",url:"namespacemembers_func.html#index_i"},
{text:"ini",url:"namespacemembers_func.html#index_i"},
{text:"inv",url:"namespacemembers_func.html#index_i"},
{text:"len",url:"namespacemembers_func.html#index_l"},
{text:"loa",url:"namespacemembers_func.html#index_l"},
{text:"loo",url:"namespacemembers_func.html#index_l"},
{text:"mat",url:"namespacemembers_func.html#index_m"},
{text:"nor",url:"namespacemembers_func.html#index_n"},
{text:"o",url:"namespacemembers_func.html#index_o"},
{text:"ort",url:"namespacemembers_func.html#index_o"},
{text:"per",url:"namespacemembers_func.html#index_p"},
{text:"poi",url:"namespacemembers_func.html#index_p"},
{text:"qua",url:"namespacemembers_func.html#index_q"},
{text:"rea",url:"namespacemembers_func.html#index_r"},
{text:"rec",url:"namespacemembers_func.html#index_r"},
{text:"rot",url:"namespacemembers_func.html#index_r"},
{text:"sav",url:"namespacemembers_func.html#index_s"},
{text:"sca",url:"namespacemembers_func.html#index_s"},
{text:"sle",url:"namespacemembers_func.html#index_s"},
{text:"tra",url:"namespacemembers_func.html#index_t"}]},
{text:"変数",url:"namespacemembers_vars.html"},
{text:"列挙型",url:"namespacemembers_enum.html"},
{text:"列挙値",url:"namespacemembers_eval.html"}]}]},
{text:"クラス",url:"annotated.html",children:[
{text:"クラス一覧",url:"annotated.html"},
{text:"クラス索引",url:"classes.html"},
{text:"クラス階層",url:"inherits.html"},
{text:"クラスメンバ",url:"functions.html",children:[
{text:"全て",url:"functions.html",children:[
{text:"a",url:"functions.html#index_a"},
{text:"app",url:"functions_a.html#index_a"},
{text:"b",url:"functions_b.html#index_b"},
{text:"buf",url:"functions_b.html#index_b"},
{text:"c",url:"functions_c.html#index_c"},
{text:"col",url:"functions_c.html#index_c"},
{text:"d",url:"functions_d.html#index_d"},
{text:"e",url:"functions_e.html#index_e"},
{text:"ele",url:"functions_e.html#index_e"},
{text:"f",url:"functions_f.html#index_f"},
{text:"g",url:"functions_g.html#index_g"},
{text:"i",url:"functions_i.html#index_i"},
{text:"l",url:"functions_l.html#index_l"},
{text:"m",url:"functions_m.html#index_m"},
{text:"mat",url:"functions_m.html#index_m"},
{text:"n",url:"functions_n.html#index_n"},
{text:"nor",url:"functions_n.html#index_n"},
{text:"o",url:"functions_o.html#index_o"},
{text:"p",url:"functions_p.html#index_p"},
{text:"poi",url:"functions_p.html#index_p"},
{text:"qua",url:"functions_q.html#index_q"},
{text:"r",url:"functions_r.html#index_r"},
{text:"s",url:"functions_s.html#index_s"},
{text:"sha",url:"functions_s.html#index_s"},
{text:"sim",url:"functions_s.html#index_s"},
{text:"t",url:"functions_t.html#index_t"},
{text:"tex",url:"functions_t.html#index_t"},
{text:"tra",url:"functions_t.html#index_t"},
{text:"tri",url:"functions_t.html#index_t"},
{text:"u",url:"functions_u.html#index_u"},
{text:"uni",url:"functions_u.html#index_u"},
{text:"vec",url:"functions_v.html#index_v"},
{text:"ver",url:"functions_v.html#index_v"},
{text:"w",url:"functions_w.html#index_w"},
{text:"~",url:"functions_~.html#index__7E"}]},
{text:"関数",url:"functions_func.html",children:[
{text:"a",url:"functions_func.html#index_a"},
{text:"app",url:"functions_func_a.html#index_a"},
{text:"b",url:"functions_func_b.html#index_b"},
{text:"buf",url:"functions_func_b.html#index_b"},
{text:"c",url:"functions_func_c.html#index_c"},
{text:"col",url:"functions_func_c.html#index_c"},
{text:"d",url:"functions_func_d.html#index_d"},
{text:"e",url:"functions_func_e.html#index_e"},
{text:"ele",url:"functions_func_e.html#index_e"},
{text:"f",url:"functions_func_f.html#index_f"},
{text:"g",url:"functions_func_g.html#index_g"},
{text:"i",url:"functions_func_i.html#index_i"},
{text:"l",url:"functions_func_l.html#index_l"},
{text:"m",url:"functions_func_m.html#index_m"},
{text:"mat",url:"functions_func_m.html#index_m"},
{text:"n",url:"functions_func_n.html#index_n"},
{text:"nor",url:"functions_func_n.html#index_n"},
{text:"o",url:"functions_func_o.html#index_o"},
{text:"p",url:"functions_func_p.html#index_p"},
{text:"poi",url:"functions_func_p.html#index_p"},
{text:"qua",url:"functions_func_q.html#index_q"},
{text:"r",url:"functions_func_r.html#index_r"},
{text:"s",url:"functions_func_s.html#index_s"},
{text:"sha",url:"functions_func_s.html#index_s"},
{text:"sim",url:"functions_func_s.html#index_s"},
{text:"t",url:"functions_func_t.html#index_t"},
{text:"tex",url:"functions_func_t.html#index_t"},
{text:"tra",url:"functions_func_t.html#index_t"},
{text:"tri",url:"functions_func_t.html#index_t"},
{text:"u",url:"functions_func_u.html#index_u"},
{text:"uni",url:"functions_func_u.html#index_u"},
{text:"vec",url:"functions_func_v.html#index_v"},
{text:"ver",url:"functions_func_v.html#index_v"},
{text:"w",url:"functions_func_w.html#index_w"},
{text:"~",url:"functions_func_~.html#index__7E"}]},
{text:"変数",url:"functions_vars.html"},
{text:"関連関数",url:"functions_rela.html"}]}]},
{text:"ファイル",url:"files.html",children:[
{text:"ファイル一覧",url:"files.html"},
{text:"ファイルメンバ",url:"globals.html",children:[
{text:"全て",url:"globals.html"},
{text:"関数",url:"globals_func.html"},
{text:"変数",url:"globals_vars.html"},
{text:"型定義",url:"globals_type.html"},
{text:"マクロ定義",url:"globals_defs.html"}]}]}]}
